### PR TITLE
Add orc-id for CLJ to file

### PR DESCRIPTION
**Pull request by Sealjay**
Inspired by @atg-abhishek - not something I was familiar with before!

### CODE REVIEW

**Review by atg-abhishek — APPROVED** [review]
LGTM!

**Comment by Sealjay** [comment]
> Is this document automatically generated from GH contributions? I'm a little nervous about this in general since the spec is from everyone in the foundation. i.e. NOT raising an objection to a PR is still contributing to the spec.

nope, this file was manually created by @atg-abhishek - I believe he was adding everyone within the foundation to it, and asked for others on the call to reach out if they noticed anyone missing. this PR is just to add my ID to the file that's there

**Comment by Sealjay** [comment]
More info @jawache  - http://bit.ly/across-workshop-community-pitch - This is related to a bigger issue, around how to identify contributors - understanding explicitly that source control is not the full picture of open source, as it excludes governance, decision making, and consensus as you mentioned. https://citation-file-format.github.io/ - this file is one approach to recognize contributors without requiring people to update the repo

**Comment by atg-abhishek** [comment]
@Sealjay I've made a [discussion](https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions/90) based on your comment above so that it doesn't get lost as we close out this PR.

**Comment by Sealjay** [comment]
Are we ok to merge, or is there some kind of RNA approval needed @atg-abhishek ?

**Comment by atg-abhishek** [comment]
I'll merge this since we have the discussion captured separately.

**Pull request merged**
