### PR TITLE
Update Software_Carbon_Intensity_Specification.md

### PR DESCRIPTION
**Pull request by benlogan**
small change to the 'Software Sustainability Actions' section. I'd like to suggest we also rename 'Energy Efficiency' to 'Software Efficiency', but we should discuss that one and I can explain my thinking...

### CODE REVIEW

**Comment by Henry-WattTime** [comment]
Looks good to me. Interested in why you think software efficiency is important.

**Review by atg-abhishek — APPROVED** [review]
LGTM!

**Comment by atg-abhishek** [comment]
> small change to the 'Software Sustainability Actions' section. I'd like to suggest we also rename 'Energy Efficiency' to 'Software Efficiency', but we should discuss that one and I can explain my thinking...

would love to hear more on this - the proposed changes are good but we should discuss the software vs. energy efficiency point

**Comment by Henry-WattTime** [comment]
WG Approved

**Pull request merged**
