### PR TITLE
Structure: Added Comparison Measure Section

### PR DESCRIPTION
**Pull request by Henry-WattTime**
Unfilled out, to be discussed

### CODE REVIEW

**Comment by atg-abhishek** [comment]
Hey @Henry-WattTime what was this about specifically?

**Comment by Henry-WattTime** [comment]
Will:
Change approach to savings between counterfactual and actual

Henry & Abhishek:
effect should be measured against the lifespan of the decision
Change/reframing forces comparison to reduce and save emissions.

Dan:
Should measure combined overall total emissions reduction
Accommodate tradeoffs
Boundary should include all effects, operating at an appropriate scope
make sure that actions may affect other teams/groups, included in scope

**Comment by Henry-WattTime** [comment]
The scope of the impact is an individual activity or decision. As an example: running and individual workload or as complex as shifting entire stack to different cloud providers.

Move standard towards measuring an impact of a decision. Less the footprint of software.

**Comment by atg-abhishek** [comment]
@Henry-WattTime given that this is still open with a few points as listed in above comments, maybe best to convert it to an issue so that we can advance and wrap up the discussion on this and then come back to the PR here once we have something to add?

**Comment by Henry-WattTime** [comment]
Merged with #28

**Pull request closed without merging**
