### PR TITLE
Update Software_Carbon_Intensity_Specification.md

### PR DESCRIPTION
**Pull request by srini1978**
Qualifying that the elements in the SCI equation scale by the same functional unit R

### CODE REVIEW

**Review by atg-abhishek — APPROVED** [review]
LGTM!

**Comment by atg-abhishek** [comment]
@Henry-WattTime mentions that we may want to address situations where software doesn't scale by the functional unit of `R` or has other multiple factors. For example, the software energy consumption might scale by number of users but the number of environments (dev and test) might change by the number of developers on the team.

**Comment by atg-abhishek** [comment]
Approved by WG during the call.

**Comment by Sealjay** [comment]
In terms of 'Various R' we had ‘Activity’ added to the dictionary, so how we identify the various operations being instrumented, to identify R, where R is variable. https://github.com/Green-Software-Foundation/Dictionary/pull/2

**Pull request merged**
