### PR TITLE
Approved SCI moved to Main

### PR DESCRIPTION
**Pull request by seanmcilroy29**
Approved/Ratified SCI moved to Main

### CODE REVIEW

**Comment by lmilbaum** [comment]
Apologies for providing my feedback where I was not asked. Did you really mean to submit a PR with 49 commits?

**Comment by seanmcilroy29** [comment]
@lmilbaum - Yes. The Spec was approved in dive so we're now updating Main to reflect this.

**Comment by lmilbaum** [comment]
> @lmilbaum - Yes. The Spec was approved in dev so we're now updating Main to reflect this.
Than maybe you would like to squash the commits

**Comment by seanmcilroy29** [comment]
@lmilbaum - Yes, squash is our normal practice.

**Comment by Henry-WattTime** [comment]
Approved by steering committee.

**Pull request merged**
