### PR TITLE
[Consistency Review] Removed repeated verbiage in Quantification method section

### PR DESCRIPTION
**Pull request by srini1978**
Removed the line from Quantification method that was redundant, Also it spoke about a "third" step when the first and second steps are not discussed in this section.

### CODE REVIEW

**Review by atg-abhishek — APPROVED** [review]
LGTM!

**Comment by jawache** [comment]
Oh the steps are mentioned in the previous sections @srini1978 :) 

First step mentioned in https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#software-boundary

The second step mentioned in https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#functional-unit-r

If we are keeping the others it makes sense to keep this one, perhaps it needs rewording to work as the first line?

**Comment by jawache** [comment]
Actually re-reading it, it does work as the first line. Would that make it match the others better @srini1978 ?

**Comment by srini1978** [comment]
> Actually re-reading it, it does work as the first line. Would that make it match the others better @srini1978 ?

Agree

**Comment by Henry-WattTime** [comment]
Approved by working group

**Pull request merged**
