### PR TITLE
added citation for the SCI

### LINKED ISSUE #81: Creating a citation for the SCI
I think it will be a good idea to add a citation file to the SCI repo as people start to reference the SCI once it is made public.

### PR DESCRIPTION
**Pull request by atg-abhishek**
Closes #81

### CODE REVIEW

**Comment by atg-abhishek** [comment]
Also, will be adding in more names as we get closer to the date, so if I've missed some names, please feel free to let me know!

**Comment by atg-abhishek** [comment]
Approved by WG during meeting

**Comment by vaughanknight** [comment]
Should we create an issue to update the citation file with everyone as a backlog item?

**Comment by atg-abhishek** [comment]
@vaughanknight I've captured it here: https://github.com/Green-Software-Foundation/software_carbon_intensity/issues/86

**Pull request merged**
