### PR TITLE
Composable SCI Scores

### PR DESCRIPTION
**Pull request by jawache**
As discussed in this discussion topic: https://github.com/Green-Software-Foundation/software_carbon_intensity/discussions/235

An SCI score can be composed from multiple other component SCI scores.

In the ideal future you come to the GSF SCI reporting catalog and lookup the SCI scores for the services you used and just plug them into your calculation.

### CODE REVIEW

**Comment by jawache** [comment]
@srini1978 this I believe is what we were talking about last meeting, let me know your thoughts?

**Review by srini1978 — APPROVED** [review]
The composable section and scaling component functional units section look good.

**Comment by Henry-WattTime** [comment]
WG approved text:

"Functional Unit Conversion

An aggregate SCI score can be composed of multiple component SCI scores.

Then as long as the Functional Unit of `R` is the same across all the component SCI scores, you can sum them up to calculate the aggregate SCI.To sum multiple component SCI scores into one aggregate score, the Functional Unit `R` MUST be the same across all components.

If the Functional Unit of a software component is not the same as the aggregate Functional Unit, then the component SCI score needs to be converted to match that of the aggregate SCI Functional Unit. You MUST disclose details of any unit conversion factors used in calculating your SCI score."

**Comment by Henry-WattTime** [comment]
WG: Approved for merge once edited

**Comment by Henry-WattTime** [comment]
WG approved

**Pull request merged**
